### ISSUE TITLE
HomeLayout with FSD

### ISSUE THREAD

**Issue by dglazkoff** [lollipopfly/polka#30]
I see an inconsistency with the documentation of the HomeLayout component
HomeLayout.vue imports components from the same layer and different slices. 
```
import { Header } from '@/widgets/header'
import { Navigation } from '@/widgets/navigation'
```

But in the documentation mention:
> Slices cannot use other slices on the same layer, and that helps with high cohesion and low coupling.

**Comment by lollipopfly** [comment]
Hey! Yes, I know about this problem. I discussed it in FSD telegram chat, we have come to a decision that we can use widget in another one if it only for show. If widget dependence of another one - no. In this case,  it is - low coupling,  not zero coupling :)

At the moment, I work on huge project, FSD is really good, but not 100% perfect.
